baseURL = "https://censorship.no/"
languageCode = "en-us"
title = "Censorship.no!"
theme = "../themes/ananke"
SectionPagesMenu = "main"
DefaultContentLanguge = "en"
Paginate = 5
enableRobotsTXT = true

[languages]
 [languages.en]
  title= "CENO Browser"
  weight = 1
  contentDir = "content/en"
 [languages.es]
  title = "Navegador CENO"
  weight = 1
  contentDir = "content/es"

[sitemap]
 priority = 0.5
 filename = "sitemap.xml"

[params]
 favicon = "images/logo_ceno.ico"
 site_logo = "images/CENO-logo-alternative.png"
 description = "CENO (Censorship.No!) is a mobile web browser for accessing the web even when the internet is down. CENO Browser is powered by Ouinet, an advanced peer-to-peer technology that connects you to a network of cooperating peers sharing a library of web content."
 github = "https://github.com/censorship-no/"
 email = "mailto:cenoers@equalit.ie"

 # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
 background_color_class = "bg-blue"

[menu]

[[menu.main]]
    identifier = "download"
    name = "Download"
    url = "/download/"
    weight = 1
    [menu.main.params]
      class = "highlight-menu-item"

[[menu.main]]
    identifier = "about"
    name = "About"
    pre = "<i class='fa fa-heart'></i>"
    url = "/about/"
    weight = 2
    [menu.main.params]
      class = "highlight-menu-item"

[[ menu.main]]
    identifier = "docs"
    name = "Docs"
    url = "/docs/"
    weight = 3
    [menu.main.params]
      class = "highlight-menu-item"

[[menu.main]]
    identifier = "user-manual"
    name = "User Manual"
    url = "/user-manual/en/"
    weight = 4
    [menu.main.params]
      class = "highlight-menu-item"

[[menu.main]]
    identifier = "support"
    name = "Support"
    url = "/support/"
    weight = 5
    [menu.main.params]
      class = "highlight-menu-item"
