baseURL = "https://censorship.no/"
languageCode = "en-us"
title = "Censorship.no!"
theme = "../themes/ananke"

DefaultContentLanguge = "en"
SectionPagesMenu = "main"
Paginate = 5
googleAnalytics = ""
enableRobotsTXT = true

[languages]
 [languages.en]
  title= "CENO browser"
  weight = 1
  contentDir = "content/en"
 [languages.es]
  title = "navegador CENO"
  weight = 1
  contentDir = "content/es"

[sitemap]
 changefreq = "monthly"
 priority = 0.5
 filename = "sitemap.xml"

[params]
 favicon = "images/logo_ceno.ico"
 site_logo = "images/logo_ceno.png"
 description = "CENO (Censorship.No!) is a mobile web browser for accessing the web even when the internet is down. CENO Browser is powered by Ouinet, an advanced peer-to-peer technology that connects you to a network of cooperating peers sharing a library of web content."
 github = "https://github.com/censorship-no/"

 # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
 background_color_class = "bg-blue"

[menu]

[[menu.main]]
    identifier = "download"
    name = "Download"
    url = "/download/"
    weight = -110
    [menu.main.params]
      class = "highlight-menu-item"

[[menu.main]]
    identifier = "about"
    name = "About"
    pre = "<i class='fa fa-heart'></i>"
    url = "/about/"
    weight = -110
    [menu.main.params]
      class = "highlight-menu-item"

[[menu.main]]
    identifier = "docs"
    name = "Documentation"
    url = "/documentation/"
    weight = -110
    [menu.main.params]
      class = "highlight-menu-item"

[[menu.main]]
    identifier = "user-manual"
    name = "User Manual"
    url = "/user-manual/en/"
    weight = -110
    [menu.main.params]
      class = "highlight-menu-item"

[[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = -110
    [menu.main.params]
      class = "highlight-menu-item"
